### ISSUE TITLE
Really Ben

### ISSUE THREAD

**Issue by williamcool7890** [Kid80/Kid80.github.io#1]
You can do better than that! A simple html and CSS file.

**Comment by Kid80** [comment]
I haven't done much with it yet.
It's for the school.

**Comment by Kid80** [comment]
Also why are you on GitHub at the moment

**Comment by williamcool7890** [comment]
I'm on GitHub because I am working with my dad and I had to clone some of his repositories

**Comment by Kid80** [comment]
Ok. You go on github a lot.
