### ISSUE TITLE
Question?

### ISSUE THREAD

**Issue by williamcool7890** [Kid80/Kid80.github.io#2]
Why are you unionizing? Please stop it. Also out of curiosity who is @Idk400, it's obvious who @TheSunWarrior is.
![image](https://user-images.githubusercontent.com/62357797/176697831-a09f7241-a3ea-425f-86f9-a46a4c42bb86.png)

**Comment by Kid80** [comment]
@Idk400 is Haines

**Comment by Kid80** [comment]
The website is at Kid80.github.io
